  runtime: nodejs
  env: flex

  runtime_config:
      operating_system: "ubuntu24"

  automatic_scaling:
    min_num_instances: 1
    max_num_instances: 3
    cool_down_period_sec: 300
    cpu_utilization:
      target_utilization: 0.8
    target_concurrent_requests: 100
  network:
    instance_tag: starship
    session_affinity: false
    forwarded_ports:
      - 5173:5173

